name: My EKS Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get cluster credentials (Improved)
        id: get-credentials
        run: |
          aws eks describe-cluster --name harisheks | jq -r '.cluster.identity.arn' > cluster-identity-arn.txt

      - name: Assume role and store credentials (Improved)
        run: |
          aws sts assume-role \
            --role-arn $(cat cluster-identity-arn.txt) \
            --role-session-name github-actions-eks-access \
            --output text | jq -r '.Credentials.AccessKeyId,.Credentials.SecretAccessKey,.Credentials.SessionToken' > eks-credentials.txt

      - name: Update kubeconfig with EKS credentials
        run: |
          aws eks update-kubeconfig --name harisheks --region ap-south-1 --kubeconfig /root/.kube/config
          kubectl config set-cluster harisheks --server=https://1E122A519D99993356246483D0C2739E.yl4.ap-south-1.eks.amazonaws.com --kubeconfig /root/.kube/config

      - name: Apply deployment.yml
        run: kubectl apply -f .github/workflows/deployment.yml -n my-namespace
