name: My EKS Workflow

on: push:
  branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI (Optional, if not pre-installed on runner)
        uses: aws-actions/install-aws-cli@v2  # Optional step

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get cluster credentials (Improved)
        id: get-credentials
        run: |
          aws eks describe-cluster --name harisheks | jq -r '.arn:aws:eks:ap-south-1:897708050608:cluster/harisheks' cluster-identity-arn.txt

      - name: Assume role and store credentials (Improved)
        run: |
          aws sts assume-role \
            --role-arn $(cat cluster-identity-arn.txt) \
            --role-session-name github-actions-eks-access \
            --output text | jq -r '.Credentials.AccessKeyId,.Credentials.SecretAccessKey,.Credentials.SessionToken' > eks-credentials.txt

      - name: Deploy Nginx to EKS (Improved)
        run: |
          source eks-credentials.txt  # Source the credentials file instead of individual exports

          kubectl apply -f nginx-deployment.yaml
