name: My EKS Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI (Optional, if not pre-installed on runner)
        uses: aws-actions/install-aws-cli@v2  # Optional step

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get cluster credentials (Improved)
        id: get-credentials
        run: |
          aws eks describe-cluster --name harisheks | jq -r '.cluster.identityArn' > cluster-identi
