name: My EKS Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v2
        with:
          aws-version: '2.28.0' # Or a compatible version

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Get cluster credentials (assuming the created role has describe rights)
        id: get-credentials
        run: |
          cluster_name=<your-eks-cluster-name>
          aws eks describe-cluster --name $cluster_name | jq -r '.cluster.identity.arn' > cluster-identity-arn.txt

      - name: Assume role and store credentials (adapt based on your needs)
        run: |
          aws sts assume-role \
            --role-arn $(cat cluster-identity-arn.txt) \
            --role-session-name github-actions-eks-access \
            --output text | jq -r '.Credentials.AccessKeyId,.Credentials.SecretAccessKey,.Credentials.SessionToken' > eks-credentials.txt

      - name: Deploy Nginx to EKS (replace with your kubectl commands)
        run: |
          export AWS_ACCESS_KEY_ID=$(cat eks-credentials.txt | head -n 1)
          export AWS_SECRET_ACCESS_KEY=$(cat eks-credentials.txt | head -n 2 | tail -n 1)
          export AWS_SESSION_TOKEN=$(cat eks-credentials.txt | tail -n 1)

          # Assuming you have kubectl configured with a cluster context
          kubectl apply -f nginx-deployment.yaml
