name: My EKS Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig with EKS credentials
        run: aws eks update-kubeconfig --name harisheks --region ap-south-1 --kubeconfig ~/.kube/config

      - name: Deploy to EKS Cluster
        run: |
          # Add your deployment commands here
          kubectl apply -f .github/workflows/deployment.yml -n my-namespace
